export const ADAPTIVE_CONFIG = {
  MIN_DIFFICULTY: 0,
  MAX_DIFFICULTY: 10,
  MOMENTUM_DECAY: 0.7,
  HYSTERESIS_THRESHOLD: 2,
  MIN_STREAK_FOR_INCREASE: 2,
  INITIAL_DIFFICULTY: 0,
  INACTIVITY_THRESHOLD_MS: 24 * 60 * 60 * 1000,
} as const;

export const SCORING_CONFIG = {
  BASE_SCORE: 100,
  DIFFICULTY_MULTIPLIER: 1.5,
  MAX_STREAK_MULTIPLIER: 3.0,
  ACCURACY_WEIGHT: 0.2,
  RECENT_WINDOW_SIZE: 10,
} as const;
